# Section 1

#### Discuss the technical details of the sentiment classification model, including data preprocessing and other key aspects of your model implementation. Your explanation should be detailed enough for your PSL classmates to replicate your results.

We used GridSearchCV for hyperparameter selection. The penalty is elasticnet, and saga is the solver. We used a max iteration count of 2000 to ensure convergence due to the large dataset size.

#### Report the AUC of your predictions on each of the 5 test datasets (refer to the evaluation metric described above), the execution time of your code, and the specifications of the computer system used (e.g., Macbook Pro, 2.53 GHz, 4GB memory, or AWS t2.large) for each of the 5 splits.

Split 1: 
- AUC Score for LogisticRegression: 0.9870942
- Execution time: 30.1842 seconds
  
Split 2:
- AUC Score for LogisticRegression: 0.9867907
- Execution time: 30.1352 seconds
  
Split 3:
- AUC Score for LogisticRegression: 0.9864187
- Execution time: 30.8156 seconds
  
Split 4:
- AUC Score for LogisticRegression: 0.9869783
- Execution time: 31.2468 seconds
  
Split 5:
- AUC Score for LogisticRegression: 0.9862662
- Execution time: 31.1201 seconds

Computer system specs: Macbook Pro, 3.2 Ghz, 32 GB memory

# Section 2

#### Provide a detailed explanation of your interpretability approach.

Obtain BERT embeddings

In [147]:
import pandas as pd
import random
from sentence_transformers import SentenceTransformer
from sklearn.linear_model import LinearRegression

import pickle
from scipy.special import expit
from sklearn.preprocessing import StandardScaler
from IPython.display import HTML
import warnings

# Suppress all UserWarnings
warnings.filterwarnings("ignore", category=UserWarning)

In [64]:
test_file_path = f'./F24_Proj3_data/split_1/test.csv'
test_y_file_path = f'./F24_Proj3_data/split_1/test_y.csv'

test = pd.read_csv(test_file_path)
test_y = pd.read_csv(test_y_file_path)

In [21]:
random.seed(42)

Grab 5 random positive reviews and 5 random negative reviews and combine them into one DataFrame.

In [22]:
positive_reviews = test[test_y['sentiment'] == 1].sample(5, random_state=42)
negative_reviews = test[test_y['sentiment'] == 0].sample(5, random_state=42)
selected_reviews = pd.concat([positive_reviews, negative_reviews])

NameError: name 'test' is not defined

Convert the DataFrame into a string array and encode it in SentenceTransformer.

In [23]:
review = selected_reviews['review'].to_numpy()

model = SentenceTransformer("all-MiniLM-L6-v2")
X_embeddings = model.encode(review)

NameError: name 'selected_reviews' is not defined

Now find a linear transformation W such that Y roughly equals X*W.

In [24]:
Y_embeddings = selected_reviews.iloc[:, 2:]

model = LinearRegression()
model.fit(X_embeddings, Y_embeddings)
W_optimal = model.coef_

intercept = model.intercept_

NameError: name 'selected_reviews' is not defined

In [25]:
print("Optimal weights (W):", W_optimal)
print("Intercept (bias):", intercept)

NameError: name 'W_optimal' is not defined

In [145]:
def highlight_sentence(sentence, probabilities, sentiment):
    relevant_probabilities = probabilities[0][sentiment]
    if (sigmoid_pred < 0.5):
        color = "rgb(255, 255, 255)"
    elif (sigmoid_pred >= 0.5):
        color = "rgb(0, 255, 0)" if sentiment == 1 else "rgb(255, 0, 0)"

    return f"<span style='background-color:{color}'>{sentence}</span>"

In [183]:
# Christians Changes

review_ids = [10466, 13120, 16917, 23582, 24055, 37586, 42355, 48453, 5868, 7451]
positive_reviews = [16917, 42355, 10466, 23582, 24055]

model = pickle.load(open('model.pkl','rb'))

final_data = []

for id in review_ids:
    embeddings_pile_path = f'SBERT_embedddings_sentences_{id}.csv'
    data = pd.read_csv(embeddings_pile_path)
    sentences = data['sentence']
    embeddings = data.iloc[:, 1:]
    highlighted_sentences = []
    sentiment = 1 if id in positive_reviews else 0
    mean_values = np.mean(embeddings, axis=0)
    centered_data = embeddings - mean_values
    for i, embedding in enumerate(centered_data.to_numpy()):
        formatted_embedding = embedding.reshape(1, -1)
        pred = model.predict_proba(formatted_embedding)
        probabilities = expit(pred)
        print(pred)

        highlighted_sentences.append(highlight_sentence(sentences[i], probabilities, sentiment))

    final_data.append({
        "id": id,
        "sentiment": sentiment,
        "sentences": "\n".join(highlighted_sentences)
    })

for data in final_data:
    print(f"ID:{data['id']}")
    print(f"Sentiment:{data['sentiment']}")
    print(f"Sentences:")
    display(HTML(data['sentences']))


[[0.00488466 0.99511534]]
[[0.19821552 0.80178448]]
[[0.04148976 0.95851024]]
[[0.05199948 0.94800052]]
[[0.44870809 0.55129191]]
[[0.47358146 0.52641854]]
[[0.0701652 0.9298348]]
[[0.01407657 0.98592343]]
[[0.04596847 0.95403153]]
[[0.18026848 0.81973152]]
[[0.08890169 0.91109831]]
[[0.05992619 0.94007381]]
[[0.17415466 0.82584534]]
[[0.22469865 0.77530135]]
[[0.07626268 0.92373732]]
[[0.20784081 0.79215919]]
[[0.09985824 0.90014176]]
[[0.20427804 0.79572196]]
[[0.09512988 0.90487012]]
[[0.05977854 0.94022146]]
[[0.24065477 0.75934523]]
[[0.01654778 0.98345222]]
[[0.04783685 0.95216315]]
[[0.17923868 0.82076132]]
[[0.14414412 0.85585588]]
[[0.13359401 0.86640599]]
[[0.15182061 0.84817939]]
[[0.00317106 0.99682894]]
[[0.13491944 0.86508056]]
[[0.3086189 0.6913811]]
[[0.28218902 0.71781098]]
[[0.03936044 0.96063956]]
[[0.01820879 0.98179121]]
[[0.0283159 0.9716841]]
[[0.45337312 0.54662688]]
[[0.39960236 0.60039764]]
[[0.067496 0.932504]]
[[0.07018155 0.92981845]]
[[0.34192247 0.6580775

ID:13120
Sentiment:0
Sentences:


ID:16917
Sentiment:1
Sentences:


ID:23582
Sentiment:1
Sentences:


ID:24055
Sentiment:1
Sentences:


ID:37586
Sentiment:0
Sentences:


ID:42355
Sentiment:1
Sentences:


ID:48453
Sentiment:0
Sentences:


ID:5868
Sentiment:0
Sentences:


ID:7451
Sentiment:0
Sentences:
